spring:
  application:
    name: OrderService

  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'shoppingcart.service'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  topic:
    orderChannel: orderChannel




    

  
