spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderdb



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/





    

  
